In [168]:
import pandas as pd
from pathlib import Path
import numpy as np

## Path configuration

In [169]:
ROOT_DIR = Path().cwd().parent
DATASET_DIR = ROOT_DIR / "dataset"
OUT_DIR= DATASET_DIR / "processed" 
CSV_FILE_PATH = OUT_DIR / "pre_clean.csv"
OUT_CSV_FILE_PATH = OUT_DIR / "clean_athlete_events.csv"
print(ROOT_DIR,"\n",DATASET_DIR,"\n",CSV_FILE_PATH,"\n",OUT_CSV_FILE_PATH)

/home/mdev/Documents/ml/olympic_medals_prediction
 /home/mdev/Documents/ml/olympic_medals_prediction/dataset
 /home/mdev/Documents/ml/olympic_medals_prediction/dataset/processed/pre_clean.csv
 /home/mdev/Documents/ml/olympic_medals_prediction/dataset/processed/clean_athlete_events.csv

## Load and Inspect

In [170]:
df = pd.read_csv(CSV_FILE_PATH)
df.head()

,Unnamed: 0,noc,season,year,athletes,athletes_female_percentage,avg_age,agv_height,avg_weight,prev_medals,prev_gold_medals,sports,events,total_medals
0,0,CHN,Summer,1932,1,0.000000,22.0,175.0,70.0,NaN,NaN,1,2,0
1,1,CHN,Summer,1936,54,0.037037,24.0,175.0,69.0,0.0,0.0,7,27,0
2,2,CHN,Summer,1948,31,0.032258,26.0,175.0,70.0,0.0,0.0,6,12,0
3,3,CHN,Summer,1952,1,0.000000,23.0,175.0,70.0,0.0,0.0,1,1,0
4,4,CHN,Summer,1984,215,0.386047,23.0,173.0,66.0,NaN,NaN,19,105,32

In [171]:
df = df.drop(columns=['Unnamed: 0'])

In [172]:
rows,columns = df.shape
print(f"Rows: {rows}\nColumns: {columns}")

Rows: 3837
Columns: 13

In [173]:
column_names = df.columns.tolist()
column_names

['noc',
 'season',
 'year',
 'athletes',
 'athletes_female_percentage',
 'avg_age',
 'agv_height',
 'avg_weight',
 'prev_medals',
 'prev_gold_medals',
 'sports',
 'events',
 'total_medals']

In [174]:
nations = df['noc'].unique().tolist()
print(f"Nations: {len(nations)}\nSamples:{nations[:10]}")

Nations: 230
Samples:['CHN', 'DEN', 'NED', 'USA', 'FIN', 'NOR', 'ROU', 'EST', 'FRA', 'MAR']

In [175]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3837 entries, 0 to 3836
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   noc                         3837 non-null   str
 1   season                      3837 non-null   str
 2   year                        3837 non-null   int64
 3   athletes                    3837 non-null   int64
 4   athletes_female_percentage  3837 non-null   float64
 5   avg_age                     3837 non-null   float64
 6   agv_height                  3837 non-null   float64
 7   avg_weight                  3837 non-null   float64
 8   prev_medals                 3218 non-null   float64
 9   prev_gold_medals            3218 non-null   float64
 10  sports                      3837 non-null   int64
 11  events                      3837 non-null   int64
 12  total_medals                3837 non-null   int64
dtypes: float64(6), int64(5), str(2)
memory usage: 389.8 KB

In [176]:
df.isna().sum()

noc                             0
season                          0
year                            0
athletes                        0
athletes_female_percentage      0
avg_age                         0
agv_height                      0
avg_weight                      0
prev_medals                   619
prev_gold_medals              619
sports                          0
events                          0
total_medals                    0
dtype: int64

In [177]:
df['total_medals'].max()

np.int64(230)

## Impute missing medals NA to Zero

In [178]:
for col in ['prev_medals','prev_gold_medals']:
    df[col] = df[col].fillna(0)

In [179]:
df.isna().sum()

noc                           0
season                        0
year                          0
athletes                      0
athletes_female_percentage    0
avg_age                       0
agv_height                    0
avg_weight                    0
prev_medals                   0
prev_gold_medals              0
sports                        0
events                        0
total_medals                  0
dtype: int64

## Label Encoding

In [180]:
df['season'] = df['season'].replace({'Summer':1,'Winter':0}).astype(int)
df['season']

0       1
1       1
2       1
3       1
4       1
       ..
3832    0
3833    0
3834    0
3835    0
3836    0
Name: season, Length: 3837, dtype: int64

## Handle Outliers

In [181]:
# exclude_cols = ['noc','season','year']
# def iqr_fun(series:pd.Series,k=3)->tuple[float,float]:
#     q1, q3 = series.quantile([0.25, 0.75])
#     iqr = q3 - q1
#     lower = q1 - k * iqr
#     upper = q3 + k * iqr
#     return lower,upper

In [182]:
# for col in column_names:
#     if col in exclude_cols:
#         continue
#     lower,upper = iqr_fun(df[col])
#     print(f"\nCapping col: {col} min: {df[col].min()} max: {df[col].max()}")
#     print("lower:",lower,"upper:",upper)
#     df[col] = df[col].clip(lower,upper)

In [183]:
df['total_medals'].max()

np.int64(230)

In [184]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3837 entries, 0 to 3836
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   noc                         3837 non-null   str
 1   season                      3837 non-null   int64
 2   year                        3837 non-null   int64
 3   athletes                    3837 non-null   int64
 4   athletes_female_percentage  3837 non-null   float64
 5   avg_age                     3837 non-null   float64
 6   agv_height                  3837 non-null   float64
 7   avg_weight                  3837 non-null   float64
 8   prev_medals                 3837 non-null   float64
 9   prev_gold_medals            3837 non-null   float64
 10  sports                      3837 non-null   int64
 11  events                      3837 non-null   int64
 12  total_medals                3837 non-null   int64
dtypes: float64(6), int64(6), str(1)
memory usage: 389.8 KB

In [185]:
df.head()

,noc,season,year,athletes,athletes_female_percentage,avg_age,agv_height,avg_weight,prev_medals,prev_gold_medals,sports,events,total_medals
0,CHN,1,1932,1,0.000000,22.0,175.0,70.0,0.0,0.0,1,2,0
1,CHN,1,1936,54,0.037037,24.0,175.0,69.0,0.0,0.0,7,27,0
2,CHN,1,1948,31,0.032258,26.0,175.0,70.0,0.0,0.0,6,12,0
3,CHN,1,1952,1,0.000000,23.0,175.0,70.0,0.0,0.0,1,1,0
4,CHN,1,1984,215,0.386047,23.0,173.0,66.0,0.0,0.0,19,105,32

In [186]:
df.duplicated().sum()

np.int64(0)

In [187]:
df.to_csv(OUT_CSV_FILE_PATH)